#
# Services definitions
#
services:
    app:
        image: kooldev/php:8.2-swoole
        command: php artisan octane:start --server=swoole --host=0.0.0.0 --port=80 --watch --poll
        restart: always
        ports:
            - "${KOOL_APP_PORT:-80}:80"
        environment:
            ASUSER: "${KOOL_ASUSER:-0}"
            UID: "${UID:-0}"
        volumes:
            - .:/app:delegated
        networks:
            - kool_local
            - kool_global
    node:
        image: kooldev/node:20
        command: ["npm", "run", "dev"]
        ports:
            - "3001:3001"
        volumes:
            - .:/app:delegated
        networks:
            - kool_local
            - kool_global
    database:
        image: mysql/mysql-server:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "${KOOL_DATABASE_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD-rootpass}"
            MYSQL_DATABASE: "${DB_DATABASE-database}"
            MYSQL_USER: "${DB_USERNAME-user}"
            MYSQL_PASSWORD: "${DB_PASSWORD-pass}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - ./mysqldb:/var/lib/mysql:delegated
        networks:
            - kool_local
        healthcheck:
            test: ["CMD", "mysqladmin", "ping"]

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - kool_local
#
# Networks definitions
#
networks:
    kool_local:
    kool_global:
        external: true
        name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
